# fly.toml app configuration file generated for privado-backend-poc on 2024-07-23T13:06:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'privado-backend-poc'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
